### ISSUE TITLE
“Back to Reminders”

### ISSUE THREAD

**Issue by itsmikerofl** [CRKatri/eggNotch#12] opened 2020-05-05 14:51 UTC
1. Open any app
2. Receive notification from another app
3. Tap notification to jump to other app
4. Observe “Return to <first app>” cut off in corner
![9C7B7BFE-8BA6-4916-B795-DD495B0BD253](https://user-images.githubusercontent.com/46585934/81080084-5a694400-8ebe-11ea-923e-977bf1ad7f49.jpeg)

**Comment by CRKatri** [comment] 2020-05-05 14:52
Duplicate of #3

**Closed as completed by CRKatri** 2020-05-05 14:52 UTC
